import type { Metadata } from "next";
import Container from "@/components/Container";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service — DripShoots",
  description: "DripShoots Terms of Service",
};

const sections = [
  {
    title: "1. Acceptance of Terms",
    body: `By accessing or using DripShoots ("Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use the Service. These terms apply to all visitors, users, and others who access or use the Service.`,
  },
  {
    title: "2. Description of Service",
    body: `DripShoots is an AI-powered fashion photography platform that transforms flat lay garment photos into professional model shoot imagery. The Service uses artificial intelligence to generate synthetic images and is intended for e-commerce, social media, and marketing use by fashion brands and retailers.`,
  },
  {
    title: "3. User Accounts",
    body: `You must create an account to access core features of the Service. You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. You agree to notify us immediately of any unauthorized use. We reserve the right to terminate accounts that violate these Terms.`,
  },
  {
    title: "4. Acceptable Use",
    body: `You may use the Service only for lawful purposes. You agree not to upload content that infringes any third-party intellectual property rights, contains harmful or illegal material, or is intended to deceive consumers. You are solely responsible for the garment images you upload and for ensuring you have the rights to use and publish the generated outputs.`,
  },
  {
    title: "5. Intellectual Property",
    body: `You retain ownership of the garment images you upload. DripShoots grants you a worldwide, non-exclusive license to use, reproduce, and publish the AI-generated images produced from your uploads for commercial and personal purposes. DripShoots retains all rights to the underlying models, software, and platform technology.`,
  },
  {
    title: "6. Credits and Billing",
    body: `Access to generation features requires an active subscription or credit balance. Subscriptions are billed in advance on a monthly or annual basis. All sales are final; credits and subscription fees are non-refundable except where required by applicable law. We reserve the right to modify pricing with 30 days notice.`,
  },
  {
    title: "7. AI-Generated Content Disclaimer",
    body: `Images generated by DripShoots are synthetic and do not depict real people. You are responsible for reviewing generated outputs before publishing and ensuring they comply with applicable advertising standards, platform policies, and local laws. DripShoots makes no warranty that generated images are suitable for any specific purpose.`,
  },
  {
    title: "8. Limitation of Liability",
    body: `To the maximum extent permitted by law, DripShoots and its affiliates shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service. Our total liability for any claim shall not exceed the amount you paid to DripShoots in the three months preceding the claim.`,
  },
  {
    title: "9. Modifications to Terms",
    body: `We reserve the right to update these Terms at any time. We will notify users of material changes via email or in-app notice. Continued use of the Service after changes take effect constitutes acceptance of the revised Terms.`,
  },
  {
    title: "10. Governing Law",
    body: `These Terms are governed by the laws of the jurisdiction in which DripShoots is incorporated, without regard to conflict of law principles. Any disputes shall be resolved in the courts of that jurisdiction.`,
  },
  {
    title: "11. Contact",
    body: `For questions about these Terms, contact us at legal@dripshoots.com.`,
  },
];

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-[#080808] text-white">
      {/* Ambient background */}
      <div className="fixed inset-0 pointer-events-none z-0">
        <div className="absolute top-[-10%] left-[20%] w-[500px] h-[500px] rounded-full bg-violet-700/8 blur-[120px]" />
        <div className="absolute bottom-[10%] right-[-5%] w-[300px] h-[300px] rounded-full bg-fuchsia-700/6 blur-[100px]" />
      </div>

      {/* Navbar */}
      <nav className="relative z-10 border-b border-white/[0.06]">
        <Container className="flex items-center justify-between py-5">
          <Link href="/" className="flex items-center gap-2">
            <div className="w-7 h-7 rounded-lg bg-violet-600 flex items-center justify-center">
              <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
                <path d="M2 12L5 7L8 10L10 5L13 2" stroke="white" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"/>
              </svg>
            </div>
            <span className="text-[17px] font-semibold tracking-tight">
              Drip<span className="text-violet-400">Shoots</span>
            </span>
          </Link>
          <Link href="/" className="text-sm text-white/40 hover:text-white transition-colors">
            ← Back to home
          </Link>
        </Container>
      </nav>

      {/* Content */}
      <section className="relative z-10 py-20">
        <Container>
          <div className="max-w-3xl mx-auto">
            {/* Header */}
            <div className="mb-14">
              <p className="text-xs text-violet-400 font-medium tracking-widest uppercase mb-3">Legal</p>
              <h1 className="text-4xl font-bold mb-4">Terms of Service</h1>
              <p className="text-white/35 text-sm">Last updated: June 2, 2026</p>
            </div>

            {/* Intro */}
            <p className="text-white/50 text-sm leading-relaxed mb-12 p-5 rounded-xl bg-white/[0.03] border border-white/[0.07]">
              Please read these Terms of Service carefully before using DripShoots. These terms constitute a legally binding agreement between you and DripShoots regarding your use of our AI fashion photography platform.
            </p>

            {/* Sections */}
            <div className="space-y-8">
              {sections.map((s) => (
                <div key={s.title} className="border-b border-white/[0.06] pb-8 last:border-0">
                  <h2 className="text-base font-semibold text-white/90 mb-3">{s.title}</h2>
                  <p className="text-white/45 text-sm leading-relaxed">{s.body}</p>
                </div>
              ))}
            </div>
          </div>
        </Container>
      </section>

      {/* Footer */}
      <footer className="relative z-10 border-t border-white/[0.06] py-8 mt-12">
        <Container className="flex flex-col md:flex-row items-center justify-between gap-4">
          <span className="text-sm font-semibold">
            Drip<span className="text-violet-400">Shoots</span>
          </span>
          <p className="text-white/25 text-xs">© 2026 DripShoots. All rights reserved.</p>
          <div className="flex gap-5 text-xs text-white/30">
            <Link href="/privacy" className="hover:text-white transition-colors">Privacy</Link>
            <Link href="/terms" className="hover:text-white transition-colors">Terms</Link>
            <a href="mailto:legal@dripshoots.com" className="hover:text-white transition-colors">Contact</a>
          </div>
        </Container>
      </footer>
    </main>
  );
}
