import type { Metadata } from "next";
import Container from "@/components/Container";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Policy — DripShoots",
  description: "DripShoots Privacy Policy",
};

const sections = [
  {
    title: "1. Introduction",
    body: `DripShoots ("we", "us", or "our") is committed to protecting your personal information. This Privacy Policy explains what data we collect, how we use it, and your rights regarding that data when you use our AI fashion photography platform.`,
  },
  {
    title: "2. Information We Collect",
    body: `We collect information you provide directly, including your name, email address, and payment information when you create an account or subscribe. We also collect the garment images you upload to generate AI photography. Additionally, we automatically collect usage data such as pages visited, features used, generation history, browser type, IP address, and device information.`,
  },
  {
    title: "3. How We Use Your Information",
    body: `We use your information to: provide and improve the Service; process payments and manage your subscription; generate AI images from your uploaded garment photos; send transactional emails such as receipts and account notices; send marketing communications (with your consent); detect and prevent fraud and abuse; and comply with legal obligations.`,
  },
  {
    title: "4. Uploaded Images",
    body: `Garment images you upload are processed by our AI models solely to generate the requested output images. We do not use your uploaded garment images to train our AI models without your explicit opt-in consent. Images are stored securely and associated with your account. You may delete your uploaded images at any time from your account dashboard.`,
  },
  {
    title: "5. AI-Generated Images",
    body: `Images generated by DripShoots are synthetic and do not contain biometric data of real individuals. Generated images are stored in your account for download and project management. We do not claim ownership of your generated images and do not sell or share them with third parties except as necessary to provide the Service (e.g., CDN delivery).`,
  },
  {
    title: "6. Sharing of Information",
    body: `We do not sell your personal data. We may share your information with: trusted service providers who assist in operating the platform (hosting, payment processing, email delivery) under strict confidentiality agreements; law enforcement or government agencies when required by applicable law; and successor entities in connection with a merger, acquisition, or sale of assets.`,
  },
  {
    title: "7. Cookies and Tracking",
    body: `We use cookies and similar technologies to maintain your session, remember your preferences, and analyze usage patterns. You can control cookie settings through your browser. Disabling cookies may affect some features of the Service. We use analytics tools to understand how users interact with the platform; this data is aggregated and anonymized.`,
  },
  {
    title: "8. Data Retention",
    body: `We retain your account data for as long as your account is active or as needed to provide the Service. If you delete your account, we will delete or anonymize your personal data within 30 days, except where retention is required by law or legitimate business necessity (e.g., billing records for 7 years).`,
  },
  {
    title: "9. Security",
    body: `We implement industry-standard security measures including encryption in transit (TLS) and at rest, access controls, and regular security audits. No system is perfectly secure; you use the Service at your own risk and should protect your account credentials carefully.`,
  },
  {
    title: "10. Your Rights",
    body: `Depending on your jurisdiction, you may have the right to access, correct, or delete your personal data; withdraw consent; object to or restrict processing; and data portability. To exercise these rights, email us at privacy@dripshoots.com. We will respond within 30 days.`,
  },
  {
    title: "11. Children's Privacy",
    body: `The Service is not directed to individuals under 13 years of age. We do not knowingly collect personal data from children under 13. If we learn we have collected such data, we will delete it promptly.`,
  },
  {
    title: "12. Changes to This Policy",
    body: `We may update this Privacy Policy from time to time. We will notify you of material changes via email or in-app notice. Continued use of the Service after the updated Policy takes effect constitutes acceptance of the changes.`,
  },
  {
    title: "13. Contact Us",
    body: `For privacy-related questions or requests, contact our Privacy team at privacy@dripshoots.com.`,
  },
];

export default function PrivacyPage() {
  return (
    <main className="min-h-screen bg-[#080808] text-white">
      {/* Ambient background */}
      <div className="fixed inset-0 pointer-events-none z-0">
        <div className="absolute top-[-10%] right-[20%] w-[500px] h-[500px] rounded-full bg-violet-700/8 blur-[120px]" />
        <div className="absolute bottom-[10%] left-[-5%] w-[300px] h-[300px] rounded-full bg-fuchsia-700/6 blur-[100px]" />
      </div>

      {/* Navbar */}
      <nav className="relative z-10 border-b border-white/[0.06]">
        <Container className="flex items-center justify-between py-5">
          <Link href="/" className="flex items-center gap-2">
            <div className="w-7 h-7 rounded-lg bg-violet-600 flex items-center justify-center">
              <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
                <path d="M2 12L5 7L8 10L10 5L13 2" stroke="white" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"/>
              </svg>
            </div>
            <span className="text-[17px] font-semibold tracking-tight">
              Drip<span className="text-violet-400">Shoots</span>
            </span>
          </Link>
          <Link href="/" className="text-sm text-white/40 hover:text-white transition-colors">
            ← Back to home
          </Link>
        </Container>
      </nav>

      {/* Content */}
      <section className="relative z-10 py-20">
        <Container>
          <div className="max-w-3xl mx-auto">
            {/* Header */}
            <div className="mb-14">
              <p className="text-xs text-violet-400 font-medium tracking-widest uppercase mb-3">Legal</p>
              <h1 className="text-4xl font-bold mb-4">Privacy Policy</h1>
              <p className="text-white/35 text-sm">Last updated: June 2, 2026</p>
            </div>

            {/* Intro */}
            <p className="text-white/50 text-sm leading-relaxed mb-12 p-5 rounded-xl bg-white/[0.03] border border-white/[0.07]">
              Your privacy matters to us. This policy describes how DripShoots collects, uses, and protects your personal data when you use our AI fashion photography platform.
            </p>

            {/* Sections */}
            <div className="space-y-8">
              {sections.map((s) => (
                <div key={s.title} className="border-b border-white/[0.06] pb-8 last:border-0">
                  <h2 className="text-base font-semibold text-white/90 mb-3">{s.title}</h2>
                  <p className="text-white/45 text-sm leading-relaxed">{s.body}</p>
                </div>
              ))}
            </div>
          </div>
        </Container>
      </section>

      {/* Footer */}
      <footer className="relative z-10 border-t border-white/[0.06] py-8 mt-12">
        <Container className="flex flex-col md:flex-row items-center justify-between gap-4">
          <span className="text-sm font-semibold">
            Drip<span className="text-violet-400">Shoots</span>
          </span>
          <p className="text-white/25 text-xs">© 2026 DripShoots. All rights reserved.</p>
          <div className="flex gap-5 text-xs text-white/30">
            <Link href="/privacy" className="hover:text-white transition-colors">Privacy</Link>
            <Link href="/terms" className="hover:text-white transition-colors">Terms</Link>
            <a href="mailto:legal@dripshoots.com" className="hover:text-white transition-colors">Contact</a>
          </div>
        </Container>
      </footer>
    </main>
  );
}
